name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull johnkegz/cicd_pipneline:latest
    - name: Delete Docker container
      # run: docker rmi -f $(docker images -q)
      run: docker rm -f testing || true
    - name: Run Docker Container
      run: sudo docker run -d --name testing -p 8080:8080 johnkegz/cicd_pipneline:latest
